version: '3.8'
services:
  backend:
    image: backend:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/postgres

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data # сохранение данных вне контейнера
    restart: unless-stopped

volumes:
  db-data: